### PR TITLE
Just updating a spelling mistake

### PR DESCRIPTION
**Pull request by bikingbadger**

### CODE REVIEW

**Comment by webistomin** [comment]
Thanks!

But you should edit source files. 
It's right here
https://github.com/lmiller1990/vue-testing-handbook/blob/master/src/.vuepress/theme/components/Sidebar.vue#L17

**Comment by bikingbadger** [comment]
So should I close this request and create a fork along with the new PR?

**Comment by webistomin** [comment]
> So should I close this request and create a fork along with the new PR?

As you wish. You can just push another one commit.

**Comment by bikingbadger** [comment]
OK. I think I figured out how to do it. Please let me know if it's how it should be. Again this is just a small change so feel free to do it and close this issue.

**Review by webistomin — APPROVED** [review]

**Comment by webistomin** [comment]
> OK. I think I figured out how to do it. Please let me know if it's how it should be. Again this is just a small change so feel free to do it and close this issue.

It's fine. Thanks!

**Pull request merged**
