### PR TITLE
WIP:Chinese translation

### PR DESCRIPTION
**Pull request by suyanhanx**

### CODE REVIEW

**Comment by lmiller1990** [comment]
Awesome... looking forward.

謝謝！

**Comment by suyanhanx** [comment]
no, i'm doing this work. Please re open this PR to let other people know i'm doing this.

**Comment by suyanhanx** [comment]
@lmiller1990

**Comment by suyanhanx** [comment]
well maybe i need to open a new PR.
you merged it too early. lol

**Comment by suyanhanx** [comment]
<https://github.com/apps/wip>
maybe you can try this app.

**Comment by lmiller1990** [comment]
Oh, my bad... all good. 

Just make a new PR :) maybe you can do one PR per article? That's what we are doing for the Japanese vers.

**Comment by suyanhanx** [comment]
@lmiller1990 ok，I'll do it like you.

**Pull request merged**
