### PR TITLE
Update rendering-a-component.html

### PR DESCRIPTION
**Pull request by Grovskiy**
Changed one word. 'сделаем' => 'сделает'

### CODE REVIEW

**Comment by webistomin** [comment]
> Changed one word. 'сделаем' => 'сделает'

You should edit `.md` files

**Comment by lmiller1990** [comment]
@Grovskiy can you update the relevant `md` file?

**Comment by Grovskiy** [comment]
@webistomin @lmiller1990 Hi, unfortunately I didn't understand how to change the file `.md` within this Pull requests, so there is a new one. I also want to know, or needs to be changed in this file `.html`, since there are already 2 fixes.
If anything, I apologize for the inconvenience.

**Comment by webistomin** [comment]
> @webistomin @lmiller1990 Hi, unfortunately I didn't understand how to change the file `.md` within this Pull requests, so there is a new one. I also want to know, or needs to be changed in this file `.html`, since there are already 2 fixes.
> If anything, I apologize for the inconvenience.

Everything is fine, just close this PR.

**Pull request closed without merging**
