### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by Junkim93**
Hello,

Korean translation is here.

Please tell me if there is something problem.

Thank you~

### CODE REVIEW

**Comment by lmiller1990** [comment]
I will review this on the weekend... awesome job @Junkim93!! It's so cool to see my book in Korean. Vue.js is popular in Korea? Or React moreso?

**Comment by Junkim93** [comment]
React is usually used more by companies than Vue.js.
Even so, Vue.js is getting popular in Korea since the old jQuery users are moving into Vue.js.
Its session receives lots of attention on FE conf of Korea.

This is just my personal view.
I think this is relative to the frontend trends like FP, TDD, TypeScript and so on.
React has a well-structured environment for that. And bigger.

So, I look forward to the Vue.js 3.0 release.

And I edited to some translations that hard to describe on Korean.

**Comment by lmiller1990** [comment]
Looks good, I'm so excited to see my book in Korean! Very impressive stuff. I'd like to visit Korea this year; if I'm in the area, I'll send you a message. :)

**Comment by Junkim93** [comment]
Cool! I'm looking forward to it :)

**Pull request merged**
