### PR TITLE
Russian translation v3

### PR DESCRIPTION
**Pull request by webistomin**
Hi! There is a new translation for Vue 3. Also made translation for Vue 2 more up-to-date. I'm not sure about documentation route. For now it's `/v3/ru`. I think you should do subdomain like it did on the official Vue.js website.

### CODE REVIEW

**Comment by lmiller1990** [comment]
Wow, that was fast.

I will look into DNS soon. This is a bit tricky, since I am hosting this on GH pages atm, I don't have a ton of flexibility with sub domains.

I might investigate moving to a dedicated domain, and perhaps host on Netlify... `vue-testing-handbook.com` is only about $15 AUD a year, and Netlify can handle the DNS. What do you think?

**Comment by webistomin** [comment]
@lmiller1990 yeah, it would be nice

**Comment by lmiller1990** [comment]
For now I say we merge it so people can make use of your hard work. I will deal with the DNS stuff at some point.

**Comment by webistomin** [comment]
@lmiller1990 👌👌👌

**Pull request merged**
