### PR TITLE
Vite vue 3 demo

### PR DESCRIPTION
**Pull request by bikingbadger**
Apologies for opening so many PR's but I'm working through the material and hopefully some of what I'm doing may help.
Vite with Vue 3 is pretty nice but still pretty new. So to learn I'm also porting over the demo app using Vite and then converting the code to using the Composition API. This is what I've done so far. I'll probably continue to do it for myself either way but if this could be useful to the project then let me know and I will continue to push commits to this PR and when done I'll let you know. Or if there is some other way that you want the process done let me know.

### CODE REVIEW

**Review by webistomin — APPROVED** [review]

**Comment by lmiller1990** [comment]
Is there a compelling reason to add this example project (it doesn't seem to be used in any of the examples, the fact is uses Vite does not seem relevant all the tests here run in Jest with jsdom) 🤔 

What is the difference between this app an the existing one?

**Comment by bikingbadger** [comment]
The main difference will be that it will be using the composition API for the code itself and probably some typescript. No reason to add it to the codebase, just thought it would be nice to have the examples that show the Composition API next to the Options API. This can also then be pointed to in the docs if someone wants to see this type of implementation.

**Comment by webistomin** [comment]
Perhaps, based on this template, it will be possible to write an article about a test with a TypeScript (https://github.com/lmiller1990/vue-testing-handbook/issues/136) and at the same time talk about Vite.

**Comment by lmiller1990** [comment]
I don't see a strong reason to add an example project that isn't referenced in the docs - I think the vast majority of readers are just looking on the actual web page for the content, not at the GH repo. The majority (all?) of the test examples are identical to the ones in the existing projects - I'm not sure of any real benefit adding another project to repo, which is just more code and dependencies to maintain and update.

I think we should keep the example projects to a minimum - the book is generally just focused on concepts and ideas, as opposed to configuring tooling.

**Comment by bikingbadger** [comment]
OK. Sound sensible.

**Pull request closed without merging**
