### PR TITLE
Update rendering-a-component.md

### PR DESCRIPTION
**Pull request by Grovskiy**
Incorrect use of the word in this context

### CODE REVIEW

**Comment by webistomin** [comment]
> Incorrect use of the word in this context

Also check out `/v3/ru/rendering-a-component.md`. Is it OK?

**Comment by lmiller1990** [comment]
I will merge this one up for now, maybe @webistomin you could fix any other oversights you see.

**Comment by webistomin** [comment]
> I will merge this one up for now, maybe @webistomin you could fix any other problems you see. I invited you to collaborate.

Yeah sure

**Comment by Grovskiy** [comment]
> > Incorrect use of the word in this context
> 
> Also check out `/v3/ru/rendering-a-component.md`. Is it OK?

I noticed a mistake when I was studying the material, this has a high priority for me, I think I am still far from version 3.

**Comment by webistomin** [comment]
> > > Incorrect use of the word in this context
> > 
> > 
> > Also check out `/v3/ru/rendering-a-component.md`. Is it OK?
> 
> I noticed a mistake when I was studying the material, this has a high priority for me, I think I am still far from version 3.

Alright, I'll check it myself.

**Pull request merged**
