### PR TITLE
Add composition api docs

### PR DESCRIPTION
**Pull request by bikingbadger**
I'm not sure if this is worth going into but I made an example of what might be a nice idea for also showing composition API code examples as Vue 3 has opened this cool feature and it might be a good place for people to see both or even be able to go back and see the examples for the composition API in the docs along the way.

The one question is whether to add this along to the docs if you agree or create a completely new chapter?
I think it would be nicer having it along the current context as you can see how both options work

### CODE REVIEW

**Review by webistomin — COMMENTED** [review]
There is already a [section for the composition api](https://lmiller1990.github.io/vue-testing-handbook/composition-api.html#the-composition-api). I found it similar.

**Comment by lmiller1990** [comment]
Cool, I think we can rework this in a more educational manner. The real lesson here is seeing if the test can help us refactor confidently. If we cannot refactor from options -> composition API, then we know that we are testing implementations details (how it works) rather than behavior (what it does). 

Could we reword it in that manner? Something like:

"Vue 3 adds another API for building components - the Composition API. One sign of a good test is we avoid testing implementation details (how the code works) but instead focus on behavior (what the code does). Let's refactor the above component and see what happens. If the test still passes, we know it's testing the right things. If it fails, we could be testing an implementation detail".

... show refactor etc ...

I think we can keep this pretty concise, and include a link to the composition API page (both in this book and the official docs).

**Comment by bikingbadger** [comment]
> There is already a [section for the composition API](https://lmiller1990.github.io/vue-testing-handbook/composition-api.html#the-composition-api). I found it similar.

My idea is that to sprinkle it in with the docs you will have an example of the Composition API next to the Options API so if you are going back over the Handbook you can see how both actually are covered by the same test and also an example of how it could be done using the Composition API. 

If you think it would be better as a completely other section that's fine too. Just let me know what to do going ahead.

**Comment by bikingbadger** [comment]
@lmiller1990 Made the changes you wanted. The idea though is to pepper in the Composition API version  throughout. This again is just me throwing out an idea. If you prefer again to keep things in a single section that could also work. I just like the idea that you can see the different ways side by side.

**Comment by lmiller1990** [comment]
thanks!

**Pull request merged**
